baseURL = "https://mmblack4.github.io/mynotes/"
languageCode = "en-us"
title = "Muthu Mani"
theme = "berbera"

pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
publishDir="docs"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
